repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_without_aggregate_type_defaults
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --args=--lockfile=false # ignore .terraform.lock.hcl
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # - id: terraform_providers_lock
      #   args:
      #     - --args=-platform=linux_amd64
      #     - --args=-platform=darwin_amd64
      #     - --args=-platform=darwin_arm64
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
