repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_without_aggregate_type_defaults
        args:
          - --hook-config=--create-file-if-not-exist=true
          - --args=--lockfile=false # ignore .terraform.lock.hcl
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # - id: terraform_providers_lock
      #   args:
      #     - --args=-platform=linux_amd64
      #     - --args=-platform=darwin_amd64
      #     - --args=-platform=darwin_arm64
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent=2]
      - id: check-ast
      - id: debug-statements
