on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-validate:
    name: Validate Example
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Semantic Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
